### ISSUE TITLE
Notification through Telegram?

### ISSUE THREAD

**Issue by zmonoid** [neptune-ml/neptune-client#70]
Any plan to do some notification with telegram, or even an App?

**Comment by jakubczakon** [comment]
Hi there @zmonoid it is a great idea.

I have written a simple telegram bot which you can ask about best/last experiments or plot charts. 
It is a part of the [neptune-contrib](https://github.com/neptune-ml/neptune-contrib) project and you can read the [documentation](https://neptune-contrib.readthedocs.io/examples/telegram_bot.html) and [code](https://github.com/neptune-ml/neptune-contrib/blob/master/neptunecontrib/bots/telegram_bot.py) if you want to.

It doesn't have notifications action but you can easily extend it.
Just add the `send_notifications` action to that class:

```python
    def send_notifications(self, bot, update):
        every 5 min:
            notifications = get_last_neptune_notifications()
            bot.send_message(chat_id=update.message.chat_id,  text=notifications)
```

If you do implement this, please contribute to the `neptune-contrib` project. 
I will add an issue there so that we wouldn't forget about this feature.

**Note**
neptune-contrib is compatible with neptune-cli (older version) not neptune-client. It should work with neptune-client but I cannot guarantee it. I will be udpating neptune-contrib soon (ETA 4.7.2019).

**Comment by zmonoid** [comment]
@jakubczakon Thanks very much~
