### ISSUE TITLE
parameters should be property

### ISSUE THREAD

**Issue by kamil-kaczmarek** [neptune-ml/neptune-client#78]
I think that experiment's parameters should be property, so I do not need to do: `npt_exp.get_parameters()['dropout']`, but I can simply do: `npt_exp.parameters['dropout']`.

What do you think: @pitercl @jakubczakon ?

**Comment by jakubczakon** [comment]
I think they should be different than property in they are a separate entity that is defined at the start and doesn't change -> those are the parameters of your experiment after all.

Now, I do like the idea of easier access via `.parameters` especially since in the neptune-lib there was `.get_experiment` but later simply you would call .parameters. I think there were reasons against, it but I don't remember right now. @lukasz-walkiewicz ?

**Comment by aniezurawski** [comment]
`get_parameters` makes a http call to Neptune so it is ensured that returned value is up-to-date. Making it a property called just `parameters` would lead to potential misleadings that it's a cheap operation.
